name: "YatoErd Container"
services:
  yatoerd:
    container_name: "yatoerd_prod"
    build:
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    volumes: []
    tmpfs: /tmp
    ports:
      # For local, wanting to test prod build
      # - "3000:3000"
      # In production, default port is port 80
      - "80:3000"
    restart: always
